[package]
name = "handcontrol-tui"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
crossterm = { workspace = true }
handcontrol-client-lib = { path = "../client-lib" }
ratatui = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
time = { workspace = true }
uuid = { workspace = true }
