package com.handcontrol.core.security

import java.nio.ByteBuffer
import java.security.MessageDigest

object VerificationCodeGenerator {
    /**
     * Generate a 6-digit verification code from certificates, server ID, and nonce
     *
     * This code is used in approval mode pairing to prevent MITM attacks.
     * Both client and server compute the same code independently.
     *
     * Algorithm:
     * 1. Compute SHA256 fingerprints of both certificates
     * 2. Combine: SHA256(client_fp || server_fp || server_id || nonce)
     * 3. Convert to hex and extract first 6 digits
     * 4. Format as XXX-XXX for readability
     *
     * The nonce is a random 32-byte value generated by the server for each pairing attempt.
     * This prevents precomputation attacks where an attacker could grind for a matching
     * certificate fingerprint offline over an extended period.
     *
     * IMPORTANT: Must match server implementation in src/security/verification.rs
     */
    fun generate(
        clientCertificateDer: ByteArray,
        serverCertificateDer: ByteArray,
        serverId: String,
        nonce: ByteArray
    ): String {
        val digest = MessageDigest.getInstance("SHA-256")

        // Compute fingerprints first
        val clientFingerprint = digest.digest(clientCertificateDer)
        digest.reset()

        val serverFingerprint = digest.digest(serverCertificateDer)
        digest.reset()

        // Combine fingerprints with server ID and nonce
        digest.update(clientFingerprint)
        digest.update(serverFingerprint)
        digest.update(serverId.toUuidBytes())
        digest.update(nonce)

        val hash = digest.digest()

        // Convert to hex and extract first 6 digits
        val hex = hash.joinToString("") { "%02x".format(it) }
        val digits = hex.filter { it.isDigit() }.take(6)

        // If we don't have enough digits (unlikely), pad with zeros
        val paddedDigits = if (digits.length < 6) {
            digits.padEnd(6, '0')
        } else {
            digits
        }

        // Format as XXX-XXX
        return "${paddedDigits.substring(0, 3)}-${paddedDigits.substring(3)}"
    }

    fun computeFingerprint(certificateDer: ByteArray): String {
        val digest = MessageDigest.getInstance("SHA-256")
        val hash = digest.digest(certificateDer)
        return "SHA256:" + hash.joinToString("") { "%02x".format(it) }
    }
}

private fun String.toUuidBytes(): ByteArray {
    return try {
        val uuid = java.util.UUID.fromString(this)
        java.nio.ByteBuffer.allocate(16)
            .putLong(uuid.mostSignificantBits)
            .putLong(uuid.leastSignificantBits)
            .array()
    } catch (e: IllegalArgumentException) {
        // Fallback to ASCII bytes if parsing fails (shouldn't happen for valid server IDs)
        this.toByteArray()
    }
}
